name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: run composer install
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --ignore-platform-reqs

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=75 --min-style=80 --disable-security-check
