name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: run composer install
      run: composer install

    - uses: docker://tienvx/phpinsights-action
      with:
        args: "-v --min-quality=80 --min-complexity=75 --min-architecture=80 --min-style=75"
