name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: run composer install
      run: composer install

    - name: run phpinsights
      run: php artisan insights
