name: PEST Tests
on: push

jobs:
  pesttests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: run composer install
      run: composer install
      
    - name: run composer dump-autoload
      run: composer dump-autoload
      
    - name: get .env file
      run: cp .env.testingCI .env

    - name: run PEST Tests
      run: ./vendor/bin/pest   
            
    env:
      APP_URL: "http://localhost"
      DB_HOST: 127.0.0.1
      DB_CONNECTION: mysql
      DB_DATABASE: testing
      DB_PORT: 33306
      DB_USER: root
