name: PEST Tests

on: push

jobs:
  pesttests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: run composer install
      run: composer install


    - name: run PEST Tests
      run: php artisan test
