name: PEST Tests
on: push
jobs:     
  pesttests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: laravel_tags
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v3
    
      - name: run composer install
        run: composer install

      - name: run composer dump-autoload
        run: composer dump-autoload

      - name: get .env file
        run: cp .env.example .env

      - name: fix prob
        run: | 
          php artisan key:generate
          php artisan cache:clear
          php artisan route:clear
          php artisan config:clear 
          php artisan view:clear 

      - name: migrate
        env:
          DB_PORT: 3306
          DB_USER: root
        run: php artisan migrate

      - name: run PEST Tests
        env:
          DB_PORT: 3306
          DB_USER: root
        run: ./vendor/bin/pest  
    
